version: '3.8'

services:
  web:
    build: ./project
    command: uvicorn app.main:app --workers 2 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=false
      - DATABASE_URL=asyncpg://postgres:postgres@web-db:5432/web_dev
      - DATABASE_TEST_URL=asyncpg://postgres:postgres@web-db:5432/web_test
    depends_on:
      - web-db

  web-db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
