# pull official base image
FROM python:3.11.8-slim

# set working directory
RUN mkdir -p /home/app \
    # create the app user
    && addgroup --system app && adduser --system --group app

ENV HOME=/home/app
ENV APP_HOME=/home/app/web
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV ENVIRONMENT prod
ENV TESTING 0

# install system dependencies
RUN apt-get update \
    && apt-get -y install netcat-traditional gcc postgresql \
    && apt-get clean

# install python dependencies
COPY ./pyproject.toml .
RUN pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install 

# add app
COPY . .

# chown all the files to the app user
RUN chown -R app:app $APP_HOME && chown -R app:app /home/app

# change to the app user
USER app

# run gunicorn
CMD gunicorn --bind 0.0.0.0:$PORT app.main:app -k uvicorn.workers.UvicornWorker
